# Generated by Django 4.0.3 on 2022-04-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_alter_destination_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='location_url',
            field=models.URLField(null=True),
        ),
    ]
