# Generated by Django 4.0.3 on 2022-04-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_destination_location_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='price',
        ),
        migrations.AddField(
            model_name='destination',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
