# Generated by Django 4.0.3 on 2022-04-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_remove_destination_price_destination_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='location_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
