# Generated by Django 4.0.3 on 2022-04-13 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_demo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='demo',
        ),
    ]
